version: '3'
services:
  conan-server:
    build: .
    ports:
      - "9300:9300"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    privileged: true
    environment:
      AWSACCESSKEYID: ${AWSACCESSKEYID}
      AWSSECRETACCESSKEY: ${AWSSECRETACCESSKEY}
    volumes:
      - ./s3bucket:/mnt/s3bucket
      - ./conan_server:/root/.conan_server
    command: >
      bash -c "s3fs ${BUCKET_NAME} /mnt/s3bucket -o url=https://s3.amazonaws.com -o use_cache=/tmp -o allow_other &&
               conan_server"
